### PR TITLE
Correctly handle floating-point "equality" in qi/numeric/real.hpp

### PR DESCRIPTION
**Pull request by gpantwrs**

### CODE REVIEW

**Comment by Kojoley** [comment]
I think neither of methods is right. The epsilon in every particular case is a problem specific value. Either the literal parser should be customizable with a comparator, or probably it should just not exist (or fine as-is), because you can do the comparison in a semantic action.

**Comment by djowel** [comment]
Not sure. Maybe make it customizable; or maybe at least make epsilon customizable with a default.

**Comment by Kojoley** [comment]
@gpantwrs would you like to update the PR with a generic solution to the problem?

**Comment by djowel** [comment]
I'd welcome a generic solution to this. For now, I'll close this and leave the code as-is.

**Pull request closed without merging**
