### PR TITLE
oss-fuzz: avoid signed integer overflow

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Comment by djowel** [comment]
I'm not sure what to make of this. Please add a test case exhibiting the issue this PR is supposed to fix.

**Comment by dtardon** [comment]
github doesn't let me attach a sample file, so I'll paste it... Compile with clang++/g++ with -fsanitize=undefined:
 
 #include <string>
 #include <boost/spirit/include/qi.hpp>
 
 int main()
 {
     namespace qi = boost::spirit::qi;
     const std::string s = "0E-2147483648";
     std::string::const_iterator it = s.begin();
     qi::phrase_parse(it, s.end(), qi::double_, qi::space);
 }

**Comment by dtardon** [comment]
And that didn't work too well either, so here it is again: https://paste.fedoraproject.org/paste/rs6RUHcwrXvY3oJeTgyHjQ .

**Comment by djowel** [comment]
Are all the Qi tests still passing with this change?

**Comment by dtardon** [comment]
@djowel - Yes, they do.

**Pull request merged**
