### PR TITLE
Allow rule.hpp to be included independently.

### PR DESCRIPTION
**Pull request by ahmedcharles**
Have rexpr include rule.hpp independently as a check.

### CODE REVIEW

**Comment by djowel** [comment]
In X3, my inclination is to simplify the include with only one include: #include <boost/spirit/home/x3.hpp>. Do you find that the situation causes a real slowdown? If so, I'd like to see some numbers on the compilation speed of both independent and single include. Most users will include most of X3 anyway.

**Comment by ahmedcharles** [comment]
That makes sense and I don't have empirical evidence that suggests that it isn't viable. Though, I imagine that eventually, someone is going to want to only #include <boost/spirit/home/x3/nonterminal/rule.hpp> rather than all of X3, especially since one of the goals of having the rule separation is improved compile times.

And I'm a big fan of every header including it's dependencies.

**Comment by djowel** [comment]
Agreed. Perhaps I can provide docs for those who want independent includes. For the tutorials though, I'd go with a single include for ease of use.

**Comment by ahmedcharles** [comment]
I understand the objection now. This change now still uses the general include for the example, but allows rule.hpp to be included while also compiling.

**Pull request merged**
