### PR TITLE
Revert "Split Spirit v2 tests"

### PR DESCRIPTION
**Pull request by Kojoley**
Reverts boostorg/spirit#290

Something strange happens to `process_jam_log` on boost test runners, they are missing information for tests and them do not appear on tests matrix.

I have looked at their logs and found that `revision`, `test-type` and `test-program` are empty:
`<test-log library="spirit" revision="" test-name="karma_regression_center_alignment" test-type="" test-program="" target-directory="boost/bin.v2/libs/spirit/test/karma/karma_regression_center_alignment.test/gcc-gnu-7.1.0/debug/threadapi-pthread" toolset="gcc-gnu-7.1.0" show-run-output="true">`

For me `run.py` generates a good one (and it shows nicely on regression matrix):
`<test-log library="spirit" revision="8e95b7" test-name="karma_regression_center_alignment" test-type="run" test-program="libs/spirit/test/karma/regression_center_alignment.cpp" target-directory="boost/bin.v2/libs/spirit/test/karma/karma_regression_center_alignment.test/msvc-14.1/debug/threadapi-win32/threading-multi" toolset="msvc-14.1" show-run-output="false">`

I do not understand what happens. The boost test system is really makes me very very sad.

### CODE REVIEW

**Comment by Kojoley** [comment]
Well, somehow if I run `b2 status/ -n -a -d0 --dump-tests --limit-tests=spirit` it show all the spirit tests, while `b2 status/ -n -a -d0 --dump-tests` does not (the ones that come from `build-project`). It blows my mind.

Interesting thing https://svn.boost.org/trac10/ticket/10288

**Comment by Kojoley** [comment]
Okay, Pool library is the cause, `b2 -n -a -d0 --exclude-tests=pool --dump-tests` or removing `libs/pool/test/Jamfile.v2` solves the problem. I digged down to their `use-valgrind`, but I do not understand what is going on.

**Comment by fhein** [comment]
@Kojoley : Off topic,  but I would like to express my great respect and recognition for all the work you are  currently doing to boost Spirit. That's great, awesome!  :)

**Comment by Kojoley** [comment]
It looks like I found the roots of the problem, waiting for boostorg/pool#18 to redeploy the reverted PR.

**Comment by Kojoley** [comment]
@fhein thanks for appreciation!

**Comment by octopus-prime** [comment]
yes, i see :-|

**Pull request merged**
