### PR TITLE
prevent unused warnings in x3

### PR DESCRIPTION
**Pull request by bebuch**
I'm not quite sure about the macro magic in "include/boost/spirit/home/x3/nonterminal/rule.hpp" :/

### CODE REVIEW

**Comment by tomilov** [comment]
Defenitely bad idea.

**Comment by bebuch** [comment]
Do you mean only the macro magic change or the pull request as a whole? I looked at it more closely and think it is okay, but it is the first time I tried to understand boost.preprocessor.

It would be nice of you if you explain why it is a bad idea. :-)

**Comment by djowel** [comment]
For unused arguments, the preferred style is to comment out the argument name instead of deleting. Example: 

bool parse(Iterator& /*first*/, Iterator const& /*last*/
-          , Context const& /*context*/, RuleContext&, Attribute& attr_) const

**Comment by bebuch** [comment]
Okay, I will do that, thank you!

**Comment by bebuch** [comment]
Close pull request. I will re-pull with simpler changes.

**Pull request closed without merging**
