### PR TITLE
Fix container traits for msvc

### LINKED ISSUE #298: X3: MSVC unordered containers `is_reservable<T>::value == false`
Until we have a good integration for boostorg/spirit in appveyor - this is what we get for now (via private appveyor account):

```
compile-c-c++ bin.v2\libs\spirit\test\x3\x3_container_support-p3.test\msvc-14.1\release\address-model-64\threadapi-win32\threading-multi\container_support.obj
container_support.cpp
libs\spirit\test\x3\container_support.cpp(181): error C2338: is_reservable problem
libs\spirit\test\x3\container_support.cpp(183): error C2338: is_reservable problem
libs\spirit\test\x3\container_support.cpp(185): error C2338: is_reservable problem
libs\spirit\test\x3\container_support.cpp(187): error C2338: is_reservable problem
```

https://ci.appveyor.com/project/octopus-prime/spirit

### PR DESCRIPTION
**Pull request by octopus-prime**
- Fixes #298 and is based on https://github.com/boostorg/spirit/commit/45902cbb4e949e7543bcf48d3a4ed1247cab4f6b provided by @Kojoley 
- Added container_support.cpp to x3 test suite again

### CODE REVIEW

**Comment by Kojoley** [comment]
That was unfriendly takeover. Good job.

**Comment by octopus-prime** [comment]
Your fix is 8 days old but still no PR.
All the time the tests for container_support are not running.
I would be happy if you could provide your fix and of course we close this PR without merge afterwards.

It is not my intend to takeover your ideas! My only intend is to run all tests. Sorry!

**Comment by Kojoley** [comment]
You are doing fine. Do not worry.

**Comment by octopus-prime** [comment]
What should happen with this PR now?

**Comment by Kojoley** [comment]
Trigger appveyor

**Comment by Kojoley** [comment]
> size_t{} was because 64bit.

Imagine, I pass my custom `struct { void resize(std::int8_t); }` container.

> 0 is unsigned int and 32bit.

That's not right. Literal will be unsigned if you use `u` suffix and `int` is *at least* 16bit.

**Comment by octopus-prime** [comment]
`signed int` you are right - and even worst...
And at least 16bit, ok. On my machine 32bit...

The main idea was to prove for existence of exact `reserve` signature in container class, wasn't it?

So here is signature from std::vector: `void reserve( size_type new_cap )`
From http://en.cppreference.com/w/cpp/container/vector/reserve

So what about `T::size_type`? That's the exact type...

And of course I think `0` is good enough - so `size_t{}` was too.

**Comment by Kojoley** [comment]
That's what you propose:
```cpp
std::vector<int> v;
v.reserve(std::vector<int>::size_type{123});
```
I wonder, you are doing it this way? It is crazy.

**Comment by octopus-prime** [comment]
LOL. So I used `size_t`. May be `std::size_t` would be better.
But `0` is fine. I imagine your custom `struct { void resize(std::int8_t); }` container.

**Pull request merged**
