### PR TITLE
X3: sequence: Fixed reference to temporary bug

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by djowel** [comment]
It should be returning the reference to the fusion sequence element. Why is it not doing that?

**Comment by Kojoley** [comment]
And it will if `deref` will return reference. But it can also return a value (for example `adt_attribute_proxy`), then there will be use after scope.

**Comment by djowel** [comment]
So we should deal with both cases.

**Comment by Kojoley** [comment]
And it already. Note that `fusion::result_of::deref` is exact return type of `deref` call.

**Comment by djowel** [comment]
Oh right!

**Comment by djowel** [comment]
I see. That add_reference is bogus indeed.

**Comment by Kojoley** [comment]
> That add_reference is bogus

Yup :-)

**Pull request merged**
