### PR TITLE
Use char32_t as unicode encoding char_type

### PR DESCRIPTION
**Pull request by theodelrieu**
Allows to use a `symbols_parser` with unicode encoding.

### CODE REVIEW

**Comment by theodelrieu** [comment]
@djowel I did let some duplicated code in the second commit, let me know where I should put this helper ;)

Kinda fixes #576 (it only fixes the default handler).

**Comment by djowel** [comment]
Nice! I've been wanting to do that for a long time! Looks good to me. I'll wait for CI to finish (hopefully it will!).

**Comment by theodelrieu** [comment]
It seems that some C++03 jobs break, I couldn't reproduce on my Linux box with `cxxflags="-std=c++03"`. The logs do not mention anything related to the patch though, are those failure happening on `develop` already?

**Comment by djowel** [comment]
> It seems that some C++03 jobs break, I couldn't reproduce on my Linux box with `cxxflags="-std=c++03"`. The logs do not mention anything related to the patch though, are those failure happening on `develop` already?

Does not seem to be related alright. Hmmm...

**Comment by djowel** [comment]
I'll merge this now. 

The CI failures look odd. It seems the same tests are passing with the same compiler in other instances. It seems the c++03 mode are the ones that are failing. Maybe it's time to get rid of c++03 mode to lessen the burden of maintenance. In any case, the issue with test is illerevant here.

**Comment by Kojoley** [comment]
No, they are not odd, the cause is `char32_t` which does not exist in C++03.

**Comment by djowel** [comment]
> No, they are not odd, the cause is `char32_t` which does not exist in C++03.

Ah darned! Of course! I should have inspected the error messages more closely. Can you fix this @theodelrieu ? I'm thinking about removing support for c++03, but that will not happen anytime soon.

**Comment by djowel** [comment]
> I'm thinking about removing support for c++03, but that will not happen anytime soon.

And that will involve a lot of work as well. So our best option is to fix this issue for now.

**Comment by djowel** [comment]
@theodelrieu , I reverted the merge for now pending the fix for c++03: https://github.com/boostorg/spirit/pull/635

**Comment by theodelrieu** [comment]
Oops, I'll fix it.

**Pull request merged**
