### PR TITLE
Cease dependence on Foreach

### PR DESCRIPTION
**Pull request by Kojoley**
I have not touch examples because they are not affecting Spirit usage and testing dependencies, and modernizing them also seems like a waste of time when we encourage to start new projects with X3 instead of Qi.

### CODE REVIEW

**Comment by djowel** [comment]
I have not looked deeper, but is there a reason why you not using the form `for(auto& x : c)` which should be a better modern substiture for `BOOST_FOREACH`?

**Comment by Kojoley** [comment]
Because Qi is still supports C++03. You think we should move on even with V2 Spirit?

**Comment by djowel** [comment]
Why are we moving from `BOOST_FOREACH` BTW, What did I miss?

**Comment by Kojoley** [comment]
Unjustified additional dependency.

**Comment by djowel** [comment]
> Unjustified additional dependency.

OK! Agreed.

**Pull request merged**
