### PR TITLE
X3: x3::variant fixes

### PR DESCRIPTION
**Pull request by Kojoley**
Supersedes #379

### CODE REVIEW

**Comment by RandomInEqualities** [comment]
I feel embarrassed about the other code now, this is so much better.

**Comment by Kojoley** [comment]
To ensure that we don't have other problems with `x3::variant` I've added tests.
Now I'm removing code bloat, because in C++14 terms `x3::variant` is an abomination.

**Comment by Kojoley** [comment]
> > To ensure that we don't have other problems with x3::variant I've added tests.
> Could you explain how it does that?

Ehmm.

> I've added tests.

For any possible operation.

> > Now I'm removing code bloat, because in C++14 terms x3::variant is an abomination.
> I agree with that. But I am not yet sure if the new code is equivalent.

I did write description for every modification, that's why there are so many commits.

> For example, 'explicit' was removed (you might have missed my comment on that).

Copy and move initialization is a valid operation for variants. I don't know why it was disabled

> (you might have missed my comment on that).

I'm sorry, but I do not see them neither on email nor on web, could you post a link?

> P.S. Please refrain from using hyperbole such as 'abomination'. These are the kind of words that work against collaboration. We can't have that here.

I'm sorry, I'm not a native speaker, actually my English is bad. But what is the problem with using hyperboles?

**Comment by Kojoley** [comment]
Well, I've hit a GCC bug that is not fixed at least for around 6 years as for now https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52869

**Comment by mjcaisse** [comment]
Hi @Kojoley -

I'll quickly address the hyperbole. It isn't the specific use of the word _abomination_ that is a problem. It is the general tone that you portray when using it. You sound rude, conceited, and make it hard to work with.

If you look at the history of `variant.hpp` you will see that it was committed May 1, 2014 by Joel. I don't know of anybody that would call Joel's work an _abomination_. There are also a few things that I might know that you haven't considered. Two weeks after that initial commit, Joel and I are going to speak on X3 in a 3-hour lecture and workshop at C++Now. At that same event, X3 will be officially released for public consumption. There is a lot going on and C++14 is young.

It may very well be that `x3::variant` is a horrible mess, poorly designed, and sloppily implemented. I doubt it is that bad ... but lets assume it is. A far better approach than declaring it an abomination or disaster (or any term that doesn't add value) is simply to point out where improvements can be made. Note problems and offer solutions.

Somebody wrote the code you are criticizing. A variety of trade-offs are made all the time: compiler support, time, compatibility, ... . You may not understand some of the constraints or it might be that the implementation needs to be improved. By being specific about your concerns and the possible improvements that can be made, we can simply make things better. 

You might be really clever and smart; however, your tone constantly portrays arrogance and an air of hard-to-work-with. Joel and I have been working together for many years. I know he has no ego and simply wants to collaborate and see the libraries improve.

It makes it easier for all of us to collaborate when we don't use hyperbole. The irony in me writing this note is that I love sarcasm and hyperbole! They just aren't very useful for collaboration.

Thank you for the effort you put into X3. It makes a difference!

**Comment by Kojoley** [comment]
@mjcaisse quick question here. Did you have a look at the patch?

**Comment by cppljevans** [comment]
On 03/22/2018 06:46 PM, Michael Caisse wrote:
> Hi @Kojoley -
> 
> I'll quickly address the hyperbole. It isn't the specific use of the word _abomination_ that is a problem. It is the general tone that you portray when using it. You sound rude, conceited, and make it hard to work with.
> 
> If you look at the history of `variant.hpp` you will see that it was committed May 1, 2014 by Joel. I don't know of anybody that would call Joel's work an _abomination_. There are also a few things that I might know that you haven't considered. Two weeks after that initial commit, Joel and I are going to speak on X3 in a 3-hour lecture and workshop at C++Now. At that same event, X3 will be officially released for public consumption. There is a lot going on and C++14 is young.
> 
> It may very well be that `x3::variant` is a horrible mess, poorly designed, and sloppily implemented. I doubt it is that bad ... but lets assume it is. A far better approach than declaring it an abomination or disaster (or any term that doesn't add value) is simply to point out where improvements can be made. Note problems and offer solutions.
> 
Yes!  I'm very curious Kojoley about how you came to your conclusion.
You might have a good point, but there no way anyone could know that
without some hint as to why.
> Somebody wrote the code you are criticizing. A variety of trade-offs are made all the time: compiler support, time, compatibility, ... . You may not understand some of the constraints or it might be that the implementation needs to be improved. By being specific about your concerns and the possible improvements that can be made, we can simply make things better.
> 
> You might be really clever and smart; however, your tone constantly portrays arrogance and an air of hard-to-work-with. Joel and I have been working together for many years. I know he has no ego and simply wants to collaborate and see the libraries improve.
> 
> It makes it easier for all of us to collaborate when we don't use hyperbole. The irony in me writing this note is that I love sarcasm and hyperbole! They just aren't very useful for collaboration.
> 
> Thank you for the effort you put into X3. It makes a difference!
> 
I concur there too.

**Comment by mjcaisse** [comment]
I've only been able to briefly look at the patch. My day has been swamped. There are some things that I have mentally flagged that I would like to follow up on, but I would normally do this on my own first. 

For example, it appears that the move constructor and move assignment have been removed. That is concerning. There are others ... and I'll probably make comments later today.

**Comment by djowel** [comment]
> Thank you for the effort you put into X3. It makes a difference!
> I concur there too.

I concur too. I do have some ego, but not that big :-) haha. No worries there.

I think the point I am trying to make is not really about me, but for all other collaborators, in general. For example, look up the word "abomination" in the dictionary. There's nothing but negativity there:

atrocity, disgrace, horror, obscenity, outrage, evil, crime, monstrosity, anathema, bane
a feeling of hatred. detestation, loathing, hatred, aversion, antipathy, revulsion, repugnance, abhorrence, odium, execration, disgust, horror, hostility

We can't have such negativity here. I too am not an english speaker. I always think twice, read twice, before I post and the dictionary always at my side.

**Comment by Kojoley** [comment]
> For example, it appears that the move constructor and move assignment have been removed. That is concerning.

https://howardhinnant.github.io/bloomberg_2016.pdf slide 30.

> I think the point I am trying to make is not really about me, but for all other collaborators, in general.

I'm sorry. It was not at any kind a personal or about. I wrote exactly

> C++14 terms `x3::variant` is an abomination.

> For example, look up the word "abomination" in the dictionary. There's nothing but negativity there:
> 
> atrocity, disgrace, horror, obscenity, outrage, evil, crime, monstrosity, anathema, bane
a feeling of hatred. detestation, loathing, hatred, aversion, antipathy, revulsion, repugnance, abhorrence, odium, execration, disgust, horror, hostility
>
> We can't have such negativity here. I too am not an english speaker. I always think twice, read twice, before I post and the dictionary always at my side.

These strange interpretations do not show up on dictionary for me https://en.oxforddictionaries.com/definition/abomination

**Comment by djowel** [comment]
> For example, look up the word "abomination" in the dictionary. There's nothing but negativity there:
> 
> atrocity, disgrace, horror, obscenity, outrage, evil, crime, monstrosity, anathema, bane
> a feeling of hatred. detestation, loathing, hatred, aversion, antipathy, revulsion, repugnance, abhorrence, odium, execration, disgust, horror, hostility
> 
> We can't have such negativity here. I too am not an english speaker. I always think twice, read twice, before I post and the dictionary always at my side.
> 
> These strange interpretations do not show up on dictionary for me https://en.oxforddictionaries.com/definition/abomination

OK, fair enough, but It's still negative:

- A thing that causes disgust or loathing.
- A feeling of hatred.

Anyway, I never thought you meant anything personal, so let's just move on :-) 

Let's go back to technical discussions :-)

**Comment by cppljevans** [comment]
On 03/22/2018 07:27 PM, Nikita Kniazev wrote:
>> For example, it appears that the move constructor and move assignment have been removed. That is concerning.
> 
> https://howardhinnant.github.io/bloomberg_2016.pdf slide 30.

I assume you mean, in particular, the Nothing row which indicates
the compiler generates the default move constructor and move assignment?

**Comment by mjcaisse** [comment]
I'm familiar with that slide. You will find similar slides in a few of my presentations in 2013 and 2014. Do you know the interaction differences between C++11, C++14, and C++17?

I believe explicit is better. It means you thought about the problem and did something about it. If you want the default, be explicit and say that is what you want.

**Comment by djowel** [comment]
> Being explicit is good; however, taking this advice to it's limit, we'd
> have to write explicitly *all* special functions instead of benefiting
> from the convenience of defaulting to the compiler generated ones.
> So, the c++ standard is encouraging bad (*not* abominable :) coding
> practices by providing default definitions of special functions?
> 
> Is that your meaning?

For x3::variant, I'd like to require this:

    void foo(my_variant_with_int const& var);

    foo (my_variant_with_int(123))

and disallow this:

    foo(123)

IMO, implicit conversion to a variant is dangerous. I just want to make sure that requirement is satisfied.

**Comment by cppljevans** [comment]
On 03/22/2018 08:53 PM, Joel de Guzman wrote:
>> Being explicit is good; however, taking this advice to it's limit, we'd
>> have to write explicitly *all* special functions instead of benefiting
>> from the convenience of defaulting to the compiler generated ones.
>> So, the c++ standard is encouraging bad (*not* abominable :) coding
>> practices by providing default definitions of special functions?
>>
>> Is that your meaning?
> 
> For x3::variant, I'd like to require this:
> 
>      void foo(my_variant_with_int const& var);
> 
>      foo (my_variant_with_int(123))
> 
> and disallow this:
> 
>      foo(123)
> 
> IMO, implicit conversion to a variant is dangerous. I just want to make sure that requirement is satisfied.
> 
Joel, FWIW, I've compiled both version of the foo call thru
Kojoley's spirit patch and the 1st compiles but the other,
the implicit conversion one, fails with an error msg
about 'no matching function' and then 'candidate function ... not viable'.

-regards,
Larry

**Comment by cppljevans** [comment]
On 03/23/2018 10:27 AM, cppljevans wrote:
> On 03/22/2018 08:53 PM, Joel de Guzman wrote:
>>> Being explicit is good; however, taking this advice to it's limit, we'd
>>> have to write explicitly *all* special functions instead of benefiting
>>> from the convenience of defaulting to the compiler generated ones.
>>> So, the c++ standard is encouraging bad (*not* abominable :) coding
>>> practices by providing default definitions of special functions?
>>>
>>> Is that your meaning?
>>
>> For x3::variant, I'd like to require this:
>>
>>       void foo(my_variant_with_int const& var);
>>
>>       foo (my_variant_with_int(123))
>>
>> and disallow this:
>>
>>       foo(123)
>>
>> IMO, implicit conversion to a variant is dangerous. I just want to make sure that requirement is satisfied.
>>
> Joel, FWIW, I've compiled both version of the foo call thru
> Kojoley's spirit patch and the 1st compiles but the other,
> the implicit conversion one, fails with an error msg
> about 'no matching function' and then 'candidate function ... not viable'.
> 
> -regards,
> Larry
> 
> 
> 
OOPS.  I didn't do the -I compile flags correctly.
After correction of the -I flags, it shows the patch
does *not* catch the implicit conversion error:
--{--cut here--
make -k all
***Without implicit conversion:
/home/evansl/dwnlds/llvm/5.0/prebuilt/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04/bin/clang++ 
-c -O0 -gdwarf-2 -stdlib=libc++  -std=c++17 -ftemplate-backtrace-limit=0 
-fdiagnostics-show-template-tree -fno-elide-type 
-fmacro-backtrace-limit=0     -I../x3-variant-fixes/include 
-I/home/evansl/prog_dev/boost/releases/ro/boost_1_65_1 
-UIMPLICIT_CONVERSION joels_preference.cpp
rm joels_preference.o
***With implicit conversion:
/home/evansl/dwnlds/llvm/5.0/prebuilt/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04/bin/clang++ 
-c -O0 -gdwarf-2 -stdlib=libc++  -std=c++17 -ftemplate-backtrace-limit=0 
-fdiagnostics-show-template-tree -fno-elide-type 
-fmacro-backtrace-limit=0     -I../x3-variant-fixes/include 
-I/home/evansl/prog_dev/boost/releases/ro/boost_1_65_1 
-DIMPLICIT_CONVERSION joels_preference.cpp

Compilation finished at Fri Mar 23 10:58:57
--}--cut here--

Sorry for noise :(

**Pull request closed without merging**
