### PR TITLE
Is this a typo in add_predicate.hpp which caused defects in x3::phrase_parse?

### PR DESCRIPTION
**Pull request by glacierx**
template <typename Iterator, typename Context
          , typename RContext, typename Attribute>
        bool parse(Iterator& first, Iterator const& last
          , Context const& context, RContext& rcontext, Attribute& /*attr*/) const
        {
            Iterator i = first;
            return this->subject.parse(i, last, context, rcontext, unused);
        }

Guys,
Please take a look at : [add_predicate.hpp](https://github.com/boostorg/spirit/blob/develop/include/boost/spirit/home/x3/operator/and_predicate.hpp)
The parameter _attr_ is commented and an unused is passed instead which will cause x3::parse_phrase left input attribute result unchanged. Is that a typo?

### CODE REVIEW

**Comment by djowel** [comment]
Not sure. Could you provide a test case that exhibits the problem?

**Comment by glacierx** [comment]
[emtpy_attribute.cpp](https://github.com/glacierx/spirit/blob/develop/test/x3/emtpy_attribute.cpp)

**Comment by djowel** [comment]
Ah, I should have said "minimal" as in: http://boost-spirit.com/home/feedback-and-support/

**Comment by glacierx** [comment]
Updated.
[empty_attribute.cpp](https://github.com/glacierx/spirit/blob/develop/test/x3/emtpy_attribute.cpp)

Or you can try the live version from [here](http://coliru.stacked-crooked.com/a/a5591ed449c88ca5)

**Comment by djowel** [comment]
Please try to make it more minimal (see the link above).

**Comment by glacierx** [comment]
[Live demo](http://coliru.stacked-crooked.com/a/f3142d4ae8e6b72f)

**Comment by glacierx** [comment]
[This](https://wandbox.org/permlink/68QiVmHjjDr9yfCV) is more stable. However this case reproduce the empty attribute but doesn't crash the attribute printing.

**Comment by glacierx** [comment]
[This](http://coliru.stacked-crooked.com/a/a5591ed449c88ca5) one crashed the attribute printing.

**Pull request merged**
