### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Flamefire**
Combines #766, #767 & #773 to verify CI passes.

Not intended to be merged, rather merge the above PRs.

### CODE REVIEW

**Comment by Flamefire** [comment]
@Lastique Boost.TypeIndex (transitively included by Boost.Variant) and Boost.Variant have dropped C++03 support, see e.g. https://github.com/boostorg/type_index/commit/b9815d397b079735b8fa1ec96ffedb99b6c553d6 & https://github.com/boostorg/variant/commit/7b45064ed8e3ddb61bc1dfb4f1ba2b5b6b7cb887
This makes at least the tests incompatible with msvc-10/11/12 and both have stopped running the appveyor test for those. Maybe Spirit should just follow.

Besides this all looks good so the individual PRs should be fine to finally merge!

**Comment by djowel** [comment]
> @Lastique Boost.TypeIndex (transitively included by Boost.Variant) and Boost.Variant have dropped C++03 support, see e.g. [boostorg/type_index@b9815d3](https://github.com/boostorg/type_index/commit/b9815d397b079735b8fa1ec96ffedb99b6c553d6) & [boostorg/variant@7b45064](https://github.com/boostorg/variant/commit/7b45064ed8e3ddb61bc1dfb4f1ba2b5b6b7cb887) This makes at least the tests incompatible with msvc-10/11/12 and both have stopped running the appveyor test for those. Maybe Spirit should just follow.
> 
> Besides this all looks good so the individual PRs should be fine to finally merge!

Agreed. Tell me if it is safe to merge now.

**Comment by Flamefire** [comment]
I have created #775 for that, so I think you can merge https://github.com/boostorg/spirit/pull/766, https://github.com/boostorg/spirit/pull/767 & https://github.com/boostorg/spirit/pull/773 

I'd suggest merging #775 & #773 first, then either #766 or #767 then rebase the other one to make sure CI now passes.

For your convenience I updated this PR with your changes to #767 and included the appveyor fix here, so if this passes here you can just merge all the above 4 and be sure CI will pass eventually.

**Comment by Flamefire** [comment]
@djowel Looks good so https://github.com/boostorg/spirit/pull/775, https://github.com/boostorg/spirit/pull/773, https://github.com/boostorg/spirit/pull/766 & https://github.com/boostorg/spirit/pull/767 can all be merged and this PR can be closed.

**Comment by djowel** [comment]
Merged. Feel free to close. Many thanks, everyone!

**Comment by djowel** [comment]
Please monitor the tests to ensure everything is fine.

**Comment by Flamefire** [comment]
All green :partying_face:

**Comment by djowel** [comment]
> All green 🥳

Wonderful!

**Comment by Lastique** [comment]
Please, don't forget to merge to master.

**Pull request closed without merging**
