### PR TITLE
Facilitate the requirements to custom floating-point type (comparison)

### PR DESCRIPTION
**Pull request by tomilov**
The change allows the user to make custom floating-point type equality comparable only. operator == (double) is not required now.

### CODE REVIEW

**Comment by tomilov** [comment]
Documentation states, that `T` should be constructible from `int` only (`T(int)`). Whether it should be possible in explicit or implicit way is unspecified, but provided expression imply, that `T` should be explicitly constructible from `int`.

**Comment by vtnerd** [comment]
I don't see where the X3 documentation lists the requirements for `T`. The v2 documentation also states this:

| boost::spirit::traits::is_equal_to_one(n)  | Return true if n is equal to 1.0. Default implementation is provided for float, double and long double. |
  -------------------------------------------------------|---------------------------------------

which would have to be updated to reflect the changes you have just made since its testing for `1`, and not `1.0`. And `T` would still need a `operator==` for itself in the default implementation of `is_equal_to_one`, which isn't listed in the documentation.

**Comment by tomilov** [comment]
I stick on [Spirit.V2 documentation](http://www.boost.org/libs/spirit/doc/html/spirit/qi/reference/numeric/real.html#spirit.qi.reference.numeric.real.minimum_expression_requirements_for__code__phrase_role__identifier__t__phrase___code_), and concentrate attention to following line of the table of `T`'s requirements:

**Expression** | **Semantics**
------------ | -------------
`T(0)` | Construct from an int.

**Comment by djowel** [comment]
I think this makes sense. Unless there are more objections, I'm willing to merge this. The documentation should be augmented with this info. And, better yet, we need tests for such custom floating-point types.

**Comment by tomilov** [comment]
If you decide to start writing tests from a scratch, then look at [this](https://github.com/tomilov/insituc/blob/master/include/floating_point_type_wrapper.hpp).

**Comment by djowel** [comment]
What's your interest with this, BTW? Are you intending to use custom numerics with Spirit?

**Comment by tomilov** [comment]
I intent to provide an example of using a wrapper of CGAL's algebraic numbers or mpfr/gmp for [my JIT-compiler project](https://github.com/tomilov/insituc) (for AST transformations and interpreter parts).

**Comment by Kojoley** [comment]
Closed and opened to kick the CI.

**Pull request closed without merging**
