### PR TITLE
Crash when print attribute in debug mode.

### PR DESCRIPTION
**Pull request by glacierx**
Please take a look. Thanks.

### CODE REVIEW

**Comment by djowel** [comment]
OK, I'll need to look into this first; reverted the merge. Could you provide a test case that exhibits the problem?

**Comment by djowel** [comment]
(reverting this for now: https://github.com/boostorg/spirit/pull/235)

**Comment by glacierx** [comment]
[emtpy_attribute.cpp](https://github.com/glacierx/spirit/blob/develop/test/x3/emtpy_attribute.cpp)

**Comment by djowel** [comment]
See my comment in the other PR

**Pull request merged**
