### PR TITLE
Update directives_tests.cpp

### PR DESCRIPTION
**Pull request by akumta**
update per ticket 10975

### CODE REVIEW

**Comment by akumta** [comment]
Per Boost ticket 10975, I have several files(about 15) that need to be updated. Is there a way for me to do this all together rather than submitting a PR for one file at a time?  Thanks.

**Comment by djowel** [comment]
You can just commit all in one PR

**Comment by akumta** [comment]
Hmm I'm not sure how I can commit all files in one PR via the browser. 
It seems like I need to submit a PR for each file edited.

**Comment by djowel** [comment]
You don't have to. See this PR, for example: https://github.com/boostorg/spirit/pull/40. Does this help: https://help.github.com/articles/creating-a-pull-request/ ?

**Comment by akumta** [comment]
It doesn't let me create a branch. It seems to filter out the branch 
name I provide.

**Comment by akumta** [comment]
I created a branch with the changes. The branch is '*ticket-10975 
<https://github.com/akumta/spirit/tree/ticket-10975>*'
Could you please take a look and see if this is correct?
I haven't yet submitted the PR.

Thanks.

**Comment by djowel** [comment]
looks like it

**Comment by akumta** [comment]
Thanks for all your help. I've just submitted the PR.

**Comment by djowel** [comment]
please close unecessary, duplicate PRs

**Comment by akumta** [comment]
I don't think I have any duplicate PR's.

**Comment by djowel** [comment]
OK. thanks.

**Pull request merged**
