### PR TITLE
fixes problem with move_to

### PR DESCRIPTION
**Pull request by hia3**
Fix bug described here - http://article.gmane.org/gmane.comp.lib.boost.devel/266211

### CODE REVIEW

**Comment by djowel** [comment]
Please explain the "problem with move_to" and how this fixes it. I'll also need some tests the exhibit the problem you mention.

**Comment by hia3** [comment]
Should I explain it here in comments of in commit description? Should I add example from http://article.gmane.org/gmane.comp.lib.boost.devel/266211 to the commit?

**Comment by hia3** [comment]
Problem was that it was trying to call this traits::move_to https://github.com/boostorg/spirit/blob/develop/include/boost/spirit/home/x3/support/traits/move_to.hpp#L171 for (in my case) Source = a1 and Dest = a1.

Message from compiler:
/..../spirit-develop/include/boost/spirit/home/x3/support/traits/move_to.hpp:172:17: note: in instantiation of function template specialization 'boost::spirit::x3::traits::detail::move_to<ast::a1, ast::a1>' requested here

Patch just adds all the forward declarations of traits::move_to so that they are vidible from detail namespace.

**Comment by hia3** [comment]
I'm not sure all those forwarding references and `std::move`s are necessary. Because 1) it can be `std::move`d when real work is done (in assignment for example) and 2) `default_transform_attribute::post` gets `attr` by reference anyway.

**Comment by djowel** [comment]
move_to in develop is work in progress. i'd be more comfortable if you can just provide a minimal test case that exhibits the problem you mention.

**Comment by hia3** [comment]
Isn't it minimal enough?

    #include <boost/spirit/home/x3.hpp>
    #include <boost/spirit/home/x3/support/ast/variant.hpp>
    #include <boost/fusion/include/define_struct_inline.hpp>

    #include <string>
    #include <vector>

    namespace ast
    {
        BOOST_FUSION_DEFINE_STRUCT_INLINE
        (
            a1,
            (std::string, v)
        )

        BOOST_FUSION_DEFINE_STRUCT_INLINE
        (
            a2,
            (a1, v1)
            (std::vector<double>, v2)
        )

        BOOST_FUSION_DEFINE_STRUCT_INLINE
        (
            a3,
            (std::vector<a2>, v1)
        )
    }

    using namespace boost::spirit::x3;

    auto a0 = rule<class i0, std::string>{} = lexeme[+alpha];
    auto a1 = rule<class i1, ast::a1>{} = a0;

    auto a2_v2 = rule<class a2_v2, std::vector<double>>{} = -(double_ % ',');
    auto a2 = rule<class i2, ast::a2>{} = a1 >> '(' >> a2_v2 >> ')';

    auto a3_v1 = rule<class a3_v1, std::vector<ast::a2>>{} = *(a2 >> ';');
    auto a3 = rule<class i3, ast::a3>{} = a3_v1;

    using data = ast::a3;

    int main()
    {
        std::string script = "";

        auto begin = script.begin();
        auto   end = script.end();

        data v;

        bool ok = (boost::spirit::x3::phrase_parse(begin, end, a3, space, v) && begin == end);
    }

**Comment by djowel** [comment]
perfect!

**Comment by djowel** [comment]
Ok, I'm going to merge this patch. Seems it's not in conflict with the work I am doing.

**Pull request merged**
