### PR TITLE
Qi: Fixed missing space in the nested template

### PR DESCRIPTION
**Pull request by Kojoley**
The bug was introduced in PR #201

### CODE REVIEW

**Comment by Kojoley** [comment]
@djowel can I ask you to merge this PR?

**Comment by djowel** [comment]
Right! :-) Thanks, Kojoley.

**Comment by mxc-commons** [comment]
I am aware that the extra space was required because of a potential ambiguity with `operator >>` parsers couldn't cope with.

Are there still compilers requiring this? I'd like to add one of these to my test environment.

**Comment by djowel** [comment]
It is required with all pre C++11 compilers (C++03)

**Comment by mxc-commons** [comment]
msvc-9.0 is pre-11 is in my environment and has no problems. That's why I
asked.

maxence business consulting gmbh
Frank Hein
Geschäftsführer
Am Weißen Stein 1
41541 Dormagen
T  +49 2133 - 2599-10
F  +49 2133 - 2599-29
M +49 151 - 54742989
E frank.hein@maxence.de

**Comment by djowel** [comment]
msvc-9.0 may be pre-c++11 but implements some C++11. Check if it has a flag with strict C++03 only. I doubt it. I don't know a strictly C++03 version of msvc. Maybe you are better off with GCC for testing C++03-isms.

**Comment by mxc-commons** [comment]
msvc can not be set precisely to a particular c++ standard. Would it make sense to define a particular "minimum compliance platform"? Qi is some days old now. Would gcc-6.1.0 set to c++03 be ok as such a reference platform?

**Comment by Kojoley** [comment]
GCC and Clang checks are made to explicitly fail on `>>` in templates if you are using `-std=c++03` or `-std=c++98`. This behavior allows you to use the latest compiler for development and do not be afraid of breaking something for compilers that not support latest C++ standard. Feel the difference from VS and undisaable M$ extensions.

**Pull request merged**
