### PR TITLE
Fixing problems related to formatting numbers

### LINKED ISSUE #628: spirit::karma::generate generates 10.0e-04, but expecting 1.0e-03
Code is:

```
std::string s;
double value = 0.00099999999999999829;
std::back_insert_iterator<std::string> sink(s);
boost::spirit::karma::generate(sink, boost::spirit::karma::real_generator<>(), value);
std::cout << s << std::endl; // outputs 10.0e-04
```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #628

### CODE REVIEW

**Comment by hkaiser** [comment]
@markusjrmueller could you please get back to us whether this fixes your issue?

**Comment by djowel** [comment]
Any further comments @markusjrmueller ? I'd like to merge this in asap.

**Comment by markusjrmueller** [comment]
As the test you added seems to work... look fine for me. Thx.

**Comment by djowel** [comment]
Thanks! merged.

**Pull request merged**
