### PR TITLE
X3: Replaced make_attribute with direct attribute construction

### PR DESCRIPTION
**Pull request by Kojoley**
If the attribute has a general way to be constructed it should already have a
default constructor.

### CODE REVIEW

**Comment by djowel** [comment]
These are customization points. There's a corresponding CP in Qi, again IIRC. I don't think this should be removed.

**Comment by Kojoley** [comment]
> These are customization points.

`make_attribute` is not advertised as a customization point anywhere and it has a strange signature to be one of.

> There's a corresponding CP in Qi

Yes there is the same thing in Qi and there are also questions about it (Karma is behaving weird IIRC, it does not pass-through attributes, something related to const problems), but I am not in the mood to touch Qi/Karma.

**Comment by djowel** [comment]
Good point. Thoughts, @hkaiser ?

**Comment by Kojoley** [comment]
If you want to know my point on Qi/Karma `make_attribute` - it should be merged into `transform_attribute`, it will solve symmetric transformation (possible, but X3 had some) problems.

**Comment by Kojoley** [comment]
Ping?

**Comment by Kojoley** [comment]
@hkaiser seems to be active on GitHub but does not answer here :-(

**Comment by hkaiser** [comment]
@Kojoley I don't know anything about X3, so I'd rather not say anything.

**Comment by Kojoley** [comment]
> @Kojoley I don't know anything about X3, so I'd rather not say anything.

There is #464 for Qi/Karma with 'backported' changes.

**Pull request merged**
