### PR TITLE
Parse into associative containers

### PR DESCRIPTION
**Pull request by octopus-prime**
Bugfix and tests for issue #287 "x3 cannot parse into associative containers anymore"

### CODE REVIEW

**Comment by octopus-prime** [comment]
The tests are useless if not executed...
We must add container_support.cpp to Jamfile again!

**Comment by djowel** [comment]
Agreed. I wonder why it's not (or was removed)  in the Jamfile!

**Comment by djowel** [comment]
Feel free to add it to the Jamfile. Seems you haven't yet in this PR?

**Comment by octopus-prime** [comment]
@Kojoley says in #287 

> but container_support.cpp does not run because it is not present on Jamfile. I just tested and it passes (not on MSVC, because of the other problem)

So I think `container_support.cpp` is not included because of the problems with MSVC?!

**Comment by djowel** [comment]
I don't think so. Anyway, If that's the case, then #ifdef it out for now. But, better yet, make it work on MSVC :-)

**Comment by octopus-prime** [comment]
So, how to get a feedback from travis and appveyor?

**Pull request merged**
