### PR TITLE
Fixes for tickets #7161 #9456 #9457

### PR DESCRIPTION
**Pull request by MaksimMyasnikov**

### CODE REVIEW

**Comment by djowel** [comment]
I assume all tests are run and passing?

**Comment by MaksimMyasnikov** [comment]
A few tests have failed due to own errors.

**Comment by djowel** [comment]
Same errors before and after the patch?

**Comment by MaksimMyasnikov** [comment]
Yes.

**Comment by djowel** [comment]
BTW, I failed to notice that that this PR is done on master. It should be done on develop. Anyway, thanks a lot!

**Comment by MaksimMyasnikov** [comment]
You're welcome :-)

**Pull request merged**
